runtime: php72

entrypoint: serve router.php

handlers:
- url: /assets
  static_dir: web/dist/assets
- url: /(.*\.(gif|png|jpeg|jpg|css|js|ico|svg))$
  static_files: web/dist/\1
  upload: web/dist/(.*)
- url: /(.*\.php)/(.*)$
  script: auto
- url: /(.*)
  static_files: web/dist/index.html
  upload: web/dist/index.html