# Use the PHP 7.3 runtime (BETA) by replacing "php72" below with "php73"
runtime: php72

# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
#
# entrypoint: serve index.php
handlers:
- url: /
  script: auto

- url: /(.+)
  script: auto
# - url: /assets
#  static_dir: web/dist/web/assets
# - url: /(.*\.(gif|png|jpeg|jpg|css|js|ico|svg))$
#  static_files: web/dist/web/\1
#  upload: web/dist/web/(.*)
# - url: /(.*\.php)/(.*)$
#  script: auto
# - url: /(.*)
#  static_files: web/dist/web/index.html
#  upload: web/dist/web/index.html
# - url: /(.*)
#  static_files: web/dist/web/index.html
#  upload: web/dist/web/index.html
# - url: .*
# script: auto