export const enum RevStat {
  DISPONIBLE = 'DISPONIBLE',
  NO_DISPONIBLE = 'NO_DISPONIBLE',
  RESERVADA = 'RESERVADA',
  MANTENIMIENTO = 'MANTENIMIENTO',
  CHECK_IN = 'CHECK-IN',
  CHECK_OUT = 'CHECK-OUT'
}


